baseURL = "https://ko.wal.ski"
languageCode = "en"
defaultContentLanguage = "en"

title = "Kristof Kowalski"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

googleAnalytics = "G-EP9QR9XLCK"

[params.author]
  name = "Kristof Kowalski"
  image = "img/krzko-8.jpg"
  links = [
    { github = "https://github.com/krzko" },
    { linkedin = "https://linkedin.com/in/kristofkowalski" },
    { x = { href = "https://x.com/krzko", text = "krzko" } },
    { link = { href = "https://fileforge.ai", text = "fileforge.ai", icon = "link", target = "_blank" } },
    { link = { href = "https://pastebase.net", text = "pastebase.net", icon = "link", target = "_blank" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

